import { z } from "zod";

export const roastModeSchema = z.enum(["easy", "normal", "hard"]);
export type RoastMode = z.infer<typeof roastModeSchema>;

export const roastModeLabels: Record<RoastMode, string> = {
  easy: "Be Gentle",
  normal: "Spicy",
  hard: "F**k It",
};

export function getRoastModeLabel(mode: RoastMode) {
  return roastModeLabels[mode];
}

const categorySchema = z.object({
  score: z.number().int().min(0).max(10),
  roast: z.string().min(1).max(280),
  explanation: z.string().min(1).max(420),
  fix: z.string().min(1).max(280),
});

export const roastResultSchema = z.object({
  attribution: z.object({
    xHandle: z.string().trim().transform((value) => value.replace(/^@/, "")).pipe(z.string().regex(/^[A-Za-z0-9_]{1,15}$/, "Use 1–15 letters, numbers, or underscores.")),
    taggingConsent: z.literal(true),
    consentedAt: z.string().optional(),
  }).optional(),
  id: z.string().optional(),
  roastMode: roastModeSchema,
  website: z.object({
    // The URL is supplied by our validated scraper, not generated by the model.
    // Avoid JSON Schema `format: uri`, which Structured Outputs does not accept.
    url: z.string().min(1).max(2048),
    name: z.string().min(1).max(100),
    domain: z.string().min(1).max(255),
    detectedProduct: z.string().max(240),
    detectedAudience: z.string().max(240),
  }),
  overallScore: z.number().int().min(0).max(100),
  verdict: z.string().min(1).max(300),
  categories: z.object({
    clarity: categorySchema,
    targetAudience: categorySchema,
    valueProposition: categorySchema,
    trust: categorySchema,
    cta: categorySchema,
  }),
  topFixes: z.array(z.object({
    title: z.string().min(1).max(100),
    explanation: z.string().min(1).max(280),
    priority: z.enum(["high", "medium", "low"]),
  })).length(3),
  shareQuote: z.string().min(1).max(240),
  createdAt: z.string().optional(),
});

export const roastRequestSchema = z.object({
  url: z.string().min(1).max(2048),
  roastMode: roastModeSchema.default("normal"),
});

export type RoastResult = z.infer<typeof roastResultSchema>;
